### ISSUE TITLE
[Documentation Request] Add Screenshots

### ISSUE THREAD

**Issue by ZenaMel** [rgrams/multiviewer#1]
Adding some screenshots of the app to the README.md would be really cool since that would make me want to download and try it out much more than just reading through the features list.

How I did it on my own repos (since clipboard-pasting images only work for issues:
1. create an issue
2. copy a screenshot via the clipboard
3. paste it into the issue
4. copy the markdown pointing to the hosted image instance
5. paste the markdown into the readme

voila, convinient way of hosting small images on github repos.

**Comment by rgrams** [comment]
Sorry, I missed this issue...

Heh, that is a good trick for hosting images without adding them to the repo itself, thanks! 

As for the main issue, well, I don't really care about marketing this to other people. I made it for my own use. And it has some problems, so I don't think it's really useful. I could add a link to the [forum thread](https://forum.defold.com/t/multi-image-viewer-tool/11991), which has a [short gif](https://forum.defold.com/uploads/default/original/2X/6/65b3bb071a006da7c834f519fa02b55646d410db.gif) of its use.

**Comment by ZenaMel** [comment]
Wow! Actually I think this looks super useful! I'd definetely want to try it out now haha.

As for "marketing":
I mean what I love about open-source projects is that by scratching your own itch you're potentially providing a tool for others who had the same itch as you and at least for me seeing how other people use software that you've written yourself is empowering and makes me wanna improve on the tool. It's just a suggestion anyway. If you're ready to create issues for the "problems" you mentionend I'd be glad to work on them with you! Cheers mate, and cool stuff.

**Comment by rgrams** [comment]
Haha, well you are right of course. I added links to the forum thread and demo gif to the readme.

The problems I mentioned were unfortunately not solve-able. Since this is made with Defold, and Defold really isn't meant to make utility applications, there are some limitations. 
* Can't shut off the update loop, so the program will still use CPU time even while in the background.
    * It's not much, but enough to noticeably slow down Photoshop while I am working.
* Can't get command-line parameters, so you can't associate the program with its ".multiview" file type and double-click on files to open them.

I actually rewrote a version of this in Love2D to solve both of these problems, but it has its own set of issues with filesystem access! Haha, you can't win. I don't think I have that version uploaded anywhere, I should put it up too.

**Comment by rgrams** [comment]
@Zenahr If you're interested, I cleaned up and uploaded my Love2D version of this here: https://github.com/rgrams/multiviewer-2

**Comment by ZenaMel** [comment]
Sweet! I'll be sure to take a look ^^
